services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /frontend/src
  backend:
    build: ./backend
    ports:
      - 8080:8080
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /backend
